---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-server-app
  namespace: argocd
spec:
  destination:
    namespace: chat
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/sangbinlee/noom.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true